Repository The-Royal-Flash/royal-flash-react, pull requests merged in 2023-08, with the labels that each got.

#25 Feat: UserContext, AuthenticationGuard, Toast, Profile API
  package.json
  pnpm-lock.yaml
  src/App.tsx
  src/api/myProfile.ts
  src/api/profile.ts
  src/components/auth/AuthenticationGuard.tsx
  src/components/auth/LoginForm.tsx
  src/components/auth/SignupForm.tsx
  src/components/auth/index.ts
  src/components/common/Loader.tsx
  src/components/common/Toast.tsx
  src/components/common/ToastStack.tsx
  src/components/common/index.ts
  src/components/layout/Header.tsx
  src/constants/toast.ts
  src/contexts/ToastContext.ts
  src/contexts/UserContext.ts
  src/pages/Login.tsx
  src/pages/Profile.tsx
  src/pages/Signup.tsx
  src/providers/ToastProvider.tsx
  src/providers/UserProvider.tsx
  src/queries/auth/fetchProfileQuery.ts
  src/queries/auth/index.ts
  src/queries/index.ts
  src/types/auth.d.ts
Labels: feat, fix

#26 Feat: RootErrorBoundary, api 변경사항 적용
  src/App.tsx
  src/components/auth/LogoAndMessage.tsx
  src/components/common/RootErrorBoundary.tsx
  src/components/common/Toast.tsx
  src/components/common/index.ts
  src/components/main/IntroductionSearch.tsx
  src/components/quizlet/QuizletDetailInfo.tsx
  src/components/search/QuizletItem.tsx
  src/constants/toast.ts
  src/pages/Profile.tsx
  src/queries/quizlet/fetchQuizletDetailQuery.ts
  src/types/quizlet.d.ts
  src/types/search.d.ts
Labels: feat, fix

#27 Feat: Study 페이지 desktop/mobile 버전
  package.json
  src/App.tsx
  src/api/index.ts
  src/api/study.ts
  src/components/index.ts
  src/components/myQuizlet/QuizletPagination.tsx
  src/components/myQuizlet/index.ts
  src/components/study/EmptyCard.tsx
  src/components/study/GhostCard.tsx
  src/components/study/ToggleGuideCard.tsx
  src/components/study/index.ts
  src/constants/index.ts
  src/constants/studyMode.ts
  src/pages/MyQuizlet.tsx
  src/pages/Study.tsx
  src/types/study.d.ts
Labels: feat, fix, Style

#28 Feat: 학습기록
  src/GlobalStyle.ts
  src/components/common/AvatarCard.tsx
  src/components/common/QuestionCarousel.tsx
  src/components/quizlet/LearningCountStatus.tsx
  src/components/quizlet/LearningStatus.tsx
  src/components/quizlet/QuizletDetailInfo.tsx
  src/components/quizlet/StudyLog.tsx
  src/components/quizlet/WrongAnswerStatus.tsx
  src/components/quizlet/index.ts
  src/components/quizlet/styles/StatusContainer.tsx
  src/components/quizlet/styles/index.ts
  src/components/search/QuizletItem.tsx
  src/types/quizlet.d.ts
  src/utils/dateFormat.ts
Labels: feat, fix, Style

#29 Feat: 학습세트 수정 버튼 및 삭제
  src/api/base.ts
  src/api/quizlet.ts
  src/api/study.ts
  src/components/quizlet/EditQuizletForm.tsx
  src/components/quizlet/QuizletDetailInfo.tsx
  src/components/search/QuizletItem.tsx
  src/components/study/EmptyCard.tsx
  src/constants/toast.ts
  src/pages/Study.tsx
  src/queries/index.ts
  src/queries/study/fetchStudyQuestionListQuery.ts
  src/queries/study/index.ts
  src/types/quizlet.d.ts
  src/types/study.d.ts
Labels: feat, Refac, fix

#30 Refac: Study 페이지 로직 분리
  src/api/study.ts
  src/components/study/Card.tsx
  src/components/study/ControlBox.tsx
  src/components/study/GhostCard.tsx
  src/components/study/StudyHeader.tsx
  src/components/study/index.ts
  src/pages/Study.tsx
  src/types/index.d.ts
  src/types/study.d.ts
Labels: Refac, fix

#31 Feat: swipe, 학습모드 종료 후의 로직 변경/구현
  src/api/study.ts
  src/components/study/AnswerCard.tsx
  src/components/study/Card.tsx
  src/components/study/ControlBox.tsx
  src/components/study/EmptyCard.tsx
  src/components/study/FinishedCard.tsx
  src/components/study/GhostCard.tsx
  src/components/study/ProgressFraction.tsx
  src/components/study/QuestionCard.tsx
  src/components/study/StudyHeader.tsx
  src/components/study/index.ts
  src/constants/study.ts
  src/pages/Study.tsx
Labels: feat, Refac, fix, Style

#32 Refac: theme, font, UI
  src/App.tsx
  src/components/auth/LoginForm.tsx
  src/components/auth/LogoAndMessage.tsx
  src/components/auth/SignupForm.tsx
  src/components/auth/styles/ButtonBox.tsx
  src/components/auth/styles/Form.tsx
  src/components/auth/styles/SubmitButton.tsx
  src/components/auth/styles/index.ts
  src/components/common/AvatarCard.tsx
  src/components/common/ExpandTooltipButton.tsx
  src/components/common/Modal.tsx
  src/components/common/QuestionCarousel.tsx
  src/components/layout/DesktopHeader.tsx
  src/components/layout/Header.tsx
  src/components/layout/Layout.tsx
  src/components/layout/MobileHeader.tsx
  src/components/layout/SpreadLogo.tsx
  src/components/layout/SpreadLogoWithText.tsx
  src/components/layout/TeamMember.tsx
  src/components/main/AnimationCardSetList.tsx
  src/components/main/IntroductionSearch.tsx
  src/components/main/SlideBox.tsx
  src/components/myQuizlet/QuizletCard.tsx
  src/components/profile/ChangePwModal.tsx
  src/components/quizlet/EditQuizletForm.tsx
  src/components/quizlet/LearningCountStatus.tsx
  src/components/quizlet/LearningStatus.tsx
  src/components/quizlet/QuizletDetailInfo.tsx
  src/components/quizlet/WrongAnswerStatus.tsx
  src/components/quizlet/styles/StyledBox.tsx
  src/components/search/QuizletItem.tsx
  src/pages/Login.tsx
  src/pages/Profile.tsx
  src/pages/Signup.tsx
  src/styles/GlobalStyle.ts
  src/styles/font.css
  src/styles/fonts/NotoSansKR-Black.eot
  src/styles/fonts/NotoSansKR-Black.ttf
  src/styles/fonts/NotoSansKR-Black.woff
  src/styles/fonts/NotoSansKR-Bold.eot
  src/styles/fonts/NotoSansKR-Bold.ttf
  src/styles/fonts/NotoSansKR-Bold.woff
  src/styles/fonts/NotoSansKR-Light.eot
  src/styles/fonts/NotoSansKR-Light.ttf
  src/styles/fonts/NotoSansKR-Light.woff
  src/styles/fonts/NotoSansKR-Medium.eot
  src/styles/fonts/NotoSansKR-Medium.ttf
  src/styles/fonts/NotoSansKR-Medium.woff
  src/styles/fonts/NotoSansKR-Regular.eot
  src/styles/fonts/NotoSansKR-Regular.ttf
  src/styles/fonts/NotoSansKR-Regular.woff
  src/styles/fonts/NotoSansKR-Thin.eot
  src/styles/fonts/NotoSansKR-Thin.ttf
  src/styles/fonts/NotoSansKR-Thin.woff
  src/styles/theme.ts
Labels: feat, Refac, fix

#33 Fix: Study 페이지 버그 수정
  src/api/study.ts
  src/components/study/Card.tsx
  src/components/study/ControlBox.tsx
  src/components/study/FinishedCard.tsx
  src/components/study/GhostCard.tsx
  src/pages/Study.tsx
Labels: feat, fix, Style

#35 Feat: MyQuizlet 페이지 API 연동
  src/api/search.ts
  src/components/index.ts
  src/components/myQuizlet/QuizletCard.tsx
  src/components/myQuizlet/QuizletPagination.tsx
  src/components/myQuizlet/Quizlets.tsx
  src/components/myQuizlet/Toggler.tsx
  src/components/search/SearchForm.tsx
  src/pages/MyQuizlet.tsx
  src/queries/index.ts
  src/queries/myQuizlet/fetchAllMyQuizletSearchQuery.ts
  src/queries/myQuizlet/index.ts
  src/styles/theme.ts
  src/types/search.d.ts
Labels: feat, fix, Style

#36 Feat: Main 페이지
  public/images/myquizlet.png
  src/components/common/ExpandTooltipButton.tsx
  src/components/layout/DesktopHeader.tsx
  src/components/layout/Header.tsx
  src/components/layout/Layout.tsx
  src/components/main/AnimationCard.tsx
  src/components/main/AnimationCardSetList.tsx
  src/components/main/BoxTitle.tsx
  src/components/main/Introduction.tsx
  src/components/main/IntroductionCreateQuizlet.tsx
  src/components/main/IntroductionMyQuizlet.tsx
  src/components/main/IntroductionSearch.tsx
  src/components/main/IntroductionStudy.tsx
  src/components/main/SlideBox.tsx
  src/components/main/index.ts
  src/components/main/styles/StyledBox.tsx
  src/components/main/styles/index.ts
  src/components/quizlet/QuizletDetailInfo.tsx
  src/pages/Main.tsx
  tsconfig.json
Labels: feat, fix, Style

#37 Feat: MyQuizletPage 페이지
  src/api/search.ts
  src/components/myQuizlet/NoResultMessage.tsx
  src/components/myQuizlet/QuizletCard.tsx
  src/components/myQuizlet/QuizletPagination.tsx
  src/components/myQuizlet/Toggler.tsx
  src/pages/MyQuizlet.tsx
  src/queries/myQuizlet/fetchAllMyQuizletSearchQuery.ts
  src/queries/myQuizlet/fetchAllMyQuizletTagsQuery.ts
  src/queries/myQuizlet/index.ts
  src/types/search.d.ts
  src/utils/dateFormat.ts
Labels: feat, fix

#38 Fix: 빌드 오류 수정
  src/components/auth/AuthenticationGuard.tsx
  src/components/common/RootErrorBoundary.tsx
  src/components/layout/Footer.tsx
  src/components/quizlet/CreateQuestionCardInputField.tsx
  src/components/quizlet/CreateQuizletForm.tsx
  src/components/quizlet/CreateQuizletInfoInputField.tsx
  src/components/quizlet/EditQuestionCardInputField.tsx
  src/components/quizlet/EditQuizletForm.tsx
  src/components/quizlet/EditQuizletInfoInputField.tsx
  src/components/quizlet/QuestionCardInputField.tsx
  src/components/quizlet/QuizletInfoInputField.tsx
  src/components/quizlet/RemoveQuestionCard.tsx
  src/components/quizlet/index.ts
  src/components/quizlet/styles/QuestionCardContainer.tsx
  src/components/quizlet/styles/QuestionCardRemoveButton.tsx
  src/components/quizlet/styles/QuizletInfoContainer.tsx
  src/components/quizlet/styles/StyledChipsInput.tsx
  src/components/quizlet/styles/StyledLoadingButton.tsx
  src/components/quizlet/styles/TextInput.tsx
  src/components/quizlet/styles/index.ts
  src/components/study/ToggleGuideCard.tsx
  src/pages/CreateQuizlet.tsx
  src/pages/QuizletDetail.tsx
  src/pages/Search.tsx
  src/queries/quizlet/fetchAllQuizletSearchQuery.ts
  src/types/quizlet.d.ts
Labels: fix

#40 Style: Study페이지 Answer/Question overflow-y 추가
  src/components/study/AnswerCard.tsx
  src/components/study/QuestionCard.tsx
Labels: Style

#39 Feat: 학습세트 관리 페이지 (off of MyQuizlet 페이지) 추가
  src/App.tsx
  src/api/search.ts
  src/components/layout/DesktopHeader.tsx
  src/components/myQuizlet/NoResultMessage.tsx
  src/components/myQuizlet/QuizletCard.tsx
  src/components/myQuizlet/Quizlets.tsx
  src/pages/MyQuizlet.tsx
  src/queries/myQuizlet/fetchAllMyQuizletSearchQuery.ts
  src/queries/myQuizlet/fetchMyOwnQuizletSearchQuery.ts
  src/queries/myQuizlet/index.ts
Labels: feat, fix

#41 -: deploy-main.yml
  .github/workflows/deploy-main.yml
Labels: Server

#42 버그 수정 및 리팩토링, main 소개 문구 추가, footer 멤버 소개
  src/components/layout/BlogLink.tsx
  src/components/layout/Footer.tsx
  src/components/layout/MemeberCard.tsx
  src/components/layout/TeamMember.tsx
  src/components/layout/TeamMemberMobile.tsx
  src/components/layout/index.ts
  src/components/main/AnimationCard.tsx
  src/components/main/IntroductionMyQuizlet.tsx
  src/components/quizlet/CreateQuizletForm.tsx
  src/components/quizlet/CreateQuizletInfoInputField.tsx
  src/components/quizlet/EditQuizletForm.tsx
  src/components/quizlet/EditQuizletInfoInputField.tsx
  src/components/search/QuizletItem.tsx
  src/pages/Search.tsx
  src/queries/quizlet/fetchAllQuizletSearchQuery.ts
  src/types/search.d.ts
Labels: feat, Refac, fix, Style

#43 Fix: 학습모드 카드 swipe 취소 로직 추가
  src/components/study/AnswerCard.tsx
  src/components/study/Card.tsx
  src/components/study/GhostCard.tsx
  src/components/study/QuestionCard.tsx
  src/constants/toast.ts
Labels: feat, fix

#45 Fix: QuizletPagination 컴포넌트 렌더링 로직 변경
  src/pages/MyQuizlet.tsx
Labels: fix

#46 Fix: Profile 페이지
  src/api/base.ts
  src/api/myProfile.ts
  src/components/layout/MobileHeader.tsx
  src/components/profile/ChangeImageModal.tsx
  src/components/profile/ChangeNicknameModal.tsx
  src/components/profile/ChangePwModal.tsx
  src/components/profile/index.ts
  src/constants/toast.ts
  src/hooks/mutation/index.ts
  src/hooks/mutation/useImageMutation.ts
  src/hooks/mutation/useNicknameMutation.ts
  src/pages/Profile.tsx
  src/types/auth.d.ts
Labels: feat, fix

#47 Feat: QuestionCarousel - Swipe 기능 추가
  src/components/common/QuestionCarousel.tsx
Labels: feat

#48 Fix: 이미지 낙관적 업데이트 onError toast_msg 수정
  src/constants/toast.ts
  src/hooks/mutation/useImageMutation.ts
Labels: fix

#49 Feat: fetchAllMyOwnQuizletTags API 연동
  src/api/search.ts
  src/pages/MyQuizlet.tsx
  src/queries/myQuizlet/fetchAllMyOwnQuizletTagsQuery.ts
  src/queries/myQuizlet/index.ts
Labels: feat

#50 Fix: Study 페이지 모바일 버전 오류
  src/components/study/AnswerCard.tsx
  src/components/study/Card.tsx
  src/components/study/ControlBox.tsx
  src/components/study/GhostCard.tsx
  src/components/study/QuestionCard.tsx
  src/components/study/StudyHeader.tsx
  src/pages/Study.tsx
Labels: fix, Style

#51 Style: MyQuizlet 페이지 모바일 레이아웃 개선
  src/components/myQuizlet/NoResultMessage.tsx
  src/components/myQuizlet/Quizlets.tsx
  src/components/myQuizlet/Toggler.tsx
  src/pages/MyQuizlet.tsx
Labels: Style

#52 AvatarImage 컴포넌트
  public/images/default-profile.png
  src/components/common/AvatarCard.tsx
  src/components/common/AvatarImage.tsx
  src/components/common/index.ts
  src/components/profile/ChangeImageModal.tsx
  src/components/quizlet/QuizletDetailInfo.tsx
  src/components/search/QuizletItem.tsx
  src/pages/Profile.tsx
Labels: feat, fix

#53 Style: NoResultMessage 모바일 버전 레이아웃 수정
  src/components/myQuizlet/NoResultMessage.tsx
Labels: Style

#54 Style: Study 페이지 모바일 버전 레이아웃 수정
  src/components/study/AnswerCard.tsx
Labels: Style

#55 Fix: 학습세트 삭제 에러 처리 로직 수정
  src/components/common/QuestionCarousel.tsx
  src/components/quizlet/EditQuizletForm.tsx
  src/components/study/AnswerCard.tsx
  src/constants/toast.ts
Labels: fix
