Repository The-Royal-Flash/royal-flash-react, pull requests merged in 2023-07, with the labels that each got.

#1 Feat: Layout, Header, Router
  .prettierrc.json
  package.json
  pnpm-lock.yaml
  public/logo/royal-flash-logo.png
  src/App.tsx
  src/GlobalStyle.ts
  src/components/Layout.tsx
  src/components/common/ExpandTooltipButton.tsx
  src/components/common/Footer.tsx
  src/components/common/Header.tsx
  src/components/common/ImageButton.tsx
  src/components/common/SpreadLogo.tsx
  src/components/common/SpreadLogoWithText.tsx
  src/components/common/index.ts
  src/components/index.ts
  src/constants/index.ts
  src/constants/theme.ts
  src/main.tsx
  src/pages/CreateQuizlet.tsx
  src/pages/EditQuizlet.tsx
  src/pages/Login.tsx
  src/pages/Main.tsx
  src/pages/MyQuizlet.tsx
  src/pages/Profile.tsx
  src/pages/QuizletDetail.tsx
  src/pages/Search.tsx
  src/pages/Signup.tsx
  src/pages/Study.tsx
  src/pages/index.ts
  tsconfig.json
Labels: feat

#2 Feat: Footer
  src/components/Layout.tsx
  src/components/common/Footer.tsx
  src/components/common/TeamMember.tsx
Labels: feat

#3 Feat: Footer, Header (Mobile)
  src/components/common/Footer.tsx
  src/components/common/Header.tsx
  src/components/common/TeamMemberMobile.tsx
  src/pages/Main.tsx
Labels: feat, Style

#4 Style: Theme 적용
  src/GlobalStyle.ts
  src/components/Layout.tsx
  src/components/common/ExpandTooltipButton.tsx
  src/components/common/Footer.tsx
  src/components/common/Header.tsx
  src/components/common/SpreadLogo.tsx
  src/components/common/SpreadLogoWithText.tsx
  src/components/common/TeamMember.tsx
  src/constants/theme.ts
Labels: Style

#5 Style: Font 설정 및 Header, Footer Style 수정
  src/GlobalStyle.ts
  src/components/common/Header.tsx
  src/components/common/SpreadLogo.tsx
  src/components/common/SpreadLogoWithText.tsx
  src/components/common/TeamMember.tsx
Labels: Style

#7 Feat:
  src/GlobalStyle.ts
  src/components/Layout.tsx
  src/components/common/ExpandTooltipButton.tsx
  src/components/common/Footer.tsx
  src/components/common/Header.tsx
  src/components/common/ImageButton.tsx
  src/components/common/Modal.tsx
  src/components/common/SpreadLogo.tsx
  src/components/common/SpreadLogoWithText.tsx
  src/components/common/TeamMember.tsx
  src/components/common/TeamMemberMobile.tsx
  src/components/common/index.ts
  src/constants/index.ts
  src/constants/study.ts
  src/constants/theme.ts
  src/types/auth.d.ts
  src/types/quizlet.d.ts
  src/utils/mediaQueries.ts
  tsconfig.json
Labels: feat, Refac, Style

#9 Feat: Main 화면, SearchForm 공통 컴포넌트
  package.json
  pnpm-lock.yaml
  public/images/search-page.png
  src/GlobalStyle.ts
  src/components/common/FadeIn.tsx
  src/components/common/SearchForm.tsx
  src/components/common/SlideScroll.tsx
  src/components/common/index.ts
  src/components/index.ts
  src/components/layout/Footer.tsx
  src/components/layout/Header.tsx
  src/components/layout/Layout.tsx
  src/components/layout/SpreadLogo.tsx
  src/components/layout/SpreadLogoWithText.tsx
  src/components/layout/TeamMember.tsx
  src/components/layout/TeamMemberMobile.tsx
  src/components/layout/index.ts
  src/components/main/AnimationCard.tsx
  src/components/main/AnimationCardSetList.tsx
  src/components/main/BoxTitle.tsx
  src/components/main/Introduction.tsx
  src/components/main/IntroductionCreateQuizlet.tsx
  src/components/main/IntroductionSearch.tsx
  src/components/main/SlideBox.tsx
  src/components/main/index.ts
  src/hooks/index.ts
  src/hooks/useCheckInView.ts
  src/pages/Main.tsx
Labels: feat, fix, Style

#8 Feat: Signup 페이지 및 Signup/Login 컴포넌트화
  src/components/auth/AuthContents.tsx
  src/components/auth/AuthForm.tsx
  src/components/auth/InterchangeButton.tsx
  src/components/auth/LogoAndMessage.tsx
  src/components/auth/index.ts
  src/pages/Login.tsx
  src/pages/Signup.tsx
  src/schemas/index.ts
  src/schemas/loginSchema.ts
  src/schemas/signupSchema.ts
Labels: feat, fix, Style

#12 -: import 수정
  src/App.tsx
  src/components/common/Modal.tsx
  src/components/common/SlideScroll.tsx
  src/components/layout/Footer.tsx
  src/components/layout/Layout.tsx
  src/components/layout/SpreadLogo.tsx
  src/components/main/AnimationCard.tsx
  src/components/main/AnimationCardSetList.tsx
  src/components/main/Introduction.tsx
  src/components/main/IntroductionCreateQuizlet.tsx
  src/components/main/IntroductionSearch.tsx
  src/components/main/SlideBox.tsx
  src/pages/Main.tsx
Labels: fix

#13 Feat: tanstack query, axios
  .gitignore
  package.json
  pnpm-lock.yaml
  src/App.tsx
  src/GlobalStyle.ts
  src/api/base.ts
  src/api/index.ts
  src/api/quizlet.ts
  src/api/search.ts
  src/components/quizlet/EditQuizletForm.tsx
  src/components/quizlet/QuestionCardForm.tsx
  src/components/quizlet/QuizletForm.tsx
  src/components/quizlet/RemoveQuestionCard.tsx
  src/components/quizlet/StyledBox.tsx
  src/components/quizlet/index.ts
  src/pages/CreateQuizlet.tsx
  src/pages/EditQuizlet.tsx
  src/queries/index.ts
  src/queries/quizlet/fetchAllQuizletSearchQuery.ts
  src/queries/quizlet/fetchQuizletDetailQuery.ts
  src/queries/quizlet/fetchQuizletQuery.ts
  src/queries/quizlet/index.ts
  src/schemas/quizletSchema.ts
  src/schemas/searchSchema.ts
  src/types/quizlet.d.ts
  src/types/response.d.ts
  src/types/search.d.ts
Labels: feat, Style, Server

#15 Feat: CreateQuizlet / EditQuizlet
  package.json
  pnpm-lock.yaml
  src/api/base.ts
  src/api/quizlet.ts
  src/components/index.ts
  src/components/quizlet/CreateQuizletForm.tsx
  src/components/quizlet/EditQuizletForm.tsx
  src/components/quizlet/QuestionCardForm.tsx
  src/components/quizlet/QuestionCardInputField.tsx
  src/components/quizlet/QuizletInfoInputField.tsx
  src/components/quizlet/RemoveQuestionCard.tsx
  src/components/quizlet/index.ts
  src/components/quizlet/styles/AddQuestionButton.tsx
  src/components/quizlet/styles/ButtonGroup.tsx
  src/components/quizlet/styles/ErrorMessage.tsx
  src/components/quizlet/styles/QuestionCardRemoveButton.tsx
  src/components/quizlet/styles/QuestionCardTitle.tsx
  src/components/quizlet/styles/StyledAddIcon.tsx
  src/components/quizlet/styles/StyledBox.tsx
  src/components/quizlet/styles/StyledButton.tsx
  src/components/quizlet/styles/StyledContainer.tsx
  src/components/quizlet/styles/StyledForm.tsx
  src/components/quizlet/styles/StyledLoadingButton.tsx
  src/components/quizlet/styles/StyledTitle.tsx
  src/components/quizlet/styles/index.ts
  src/pages/CreateQuizlet.tsx
  src/pages/EditQuizlet.tsx
  src/queries/quizlet/fetchAllQuizletSearchQuery.ts
  src/schemas/quizletSchema.ts
  src/types/index.d.ts
  src/types/quizlet.d.ts
  src/types/response.d.ts
Labels: feat, Refac, fix, Style

#16 Feat: Quizlet Detail
  src/api/quizlet.ts
  src/api/search.ts
  src/components/common/AvatarCard.tsx
  src/components/common/QuestionCarousel.tsx
  src/components/common/index.ts
  src/components/quizlet/QuizletDetailInfo.tsx
  src/components/quizlet/index.ts
  src/pages/QuizletDetail.tsx
  src/pages/Search.tsx
  src/queries/quizlet/fetchAllQuizletSearchQuery.ts
  src/queries/quizlet/fetchQuizletDetailQuery.ts
  src/types/quizlet.d.ts
  src/types/search.d.ts
Labels: feat

#17 Feat: 로그인. 회원가입 API 연동
  src/api/auth.ts
  src/api/index.ts
  src/components/auth/LoginForm.tsx
  src/components/auth/SignupForm.tsx
  src/types/auth.d.ts
Labels: feat

#18 Feat; 로그인, 로그아웃 API 전체 연동
  package.json
  pnpm-lock.yaml
  src/App.tsx
  src/api/auth.ts
  src/components/auth/FormInput.tsx
  src/components/auth/LoginForm.tsx
  src/components/auth/SignupForm.tsx
  src/components/auth/index.ts
  src/components/layout/Header.tsx
  src/constants/authLabels.ts
  src/constants/index.ts
  src/contexts/UserContext.ts
  src/hooks/index.ts
  src/hooks/useDebounce.ts
  src/types/auth.d.ts
Labels: feat, Refac, fix

#19 Feat: 프로필 페이지 및 닉네임 변경 기능
  src/App.tsx
  src/api/auth.ts
  src/api/index.ts
  src/api/myProfile.ts
  src/components/auth/FormInput.tsx
  src/components/auth/LoginForm.tsx
  src/components/auth/SignupForm.tsx
  src/components/layout/Header.tsx
  src/pages/Profile.tsx
  src/schemas/authSchema.ts
  src/types/auth.d.ts
Labels: feat, fix, Style

#23 Feat: ChangePwModal 컴포넌트 추가
  src/components/index.ts
  src/components/profile/ChangePwModal.tsx
  src/components/profile/index.ts
Labels: feat, fix

#24 Feat: Search
  src/GlobalStyle.ts
  src/api/search.ts
  src/components/common/SearchForm.tsx
  src/components/common/index.ts
  src/components/index.ts
  src/components/search/QuizletItem.tsx
  src/components/search/SearchForm.tsx
  src/components/search/index.ts
  src/pages/MyQuizlet.tsx
  src/pages/Search.tsx
  src/queries/quizlet/fetchAllQuizletSearchQuery.ts
  src/queries/quizlet/fetchQuizletTagsQuery.ts
  src/queries/quizlet/index.ts
  src/types/search.d.ts
Labels: feat, Style
